name: Deploy HTML/CSS/JS to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pega o código do repositório
      - name: Checkout código
        uses: actions/checkout@v3

      # 2️⃣ Upload via FTP para Hostinger
      - name: Upload via FTP para Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # raiz do repositório
          server-dir: /public_html/

          # Ignorar arquivos desnecessários
          exclude: |
            .git*
            .github*
            README.md
            node_modules*
